version: '3'

services:
  is_ex_ts_tf_jupyter:
    build:
      context: .
      dockerfile: ./docker/tf_jupyter/Dockerfile
    container_name: is_ex_ts_tf_jupyter
    hostname: is_ex_ts_tf_jupyter
    image: is_ex_ts_tf_jupyter:0.1
    environment:
      - PASSWORD=y0urPa55w0rd
    ports:
      - 8888:8888
      - 6006:6006
    volumes:
      - ./notebooks:/notebooks/
    networks:
      - is_ex_ts_network

  is_ex_ts_nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: is_ex_ts_nginx
    image: is_ex_ts_nginx:0.1
    environment:
      - SITE=jupyter
    ports:
      - "8080:80"
    links:
      - is_ex_ts_tf_jupyter
    networks:
      - is_ex_ts_network

networks:
  is_ex_ts_network:
    driver: bridge

